[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "chess_contract"

[dependencies]
chess_abi = { path = "../chess_abi" }
lib_chess = { path = "../lib_chess" }
